apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
spec:
  selector:
    matchLabels:
      app: node-app
  replicas: 2
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: alejomayasw/hello-world-node-test:0.0.2
        ports:
        - containerPort: 8083
